apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  name: eventsubscriptions.event.redhat-cop.io
spec:
  group: event.redhat-cop.io
  names:
    kind: EventSubscription
    listKind: EventSubscriptionList
    plural: eventsubscriptions
    singular: eventsubscription
    shortNames:
      - eventsub
      - es
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          type: string
        kind:
          type: string
        metadata:
          type: object
        spec:
          type: object
        status:
          type: object
  version: v1
  versions:
  - name: v1
    served: true
    storage: true
