apiVersion: notify.redhat-cop.io/v1
kind: Notifier
metadata:
  name: slack-notify
spec:
  slack:
    webhook_url: https://hooks.slack.com/services/foo/bar
    username: my_cluster
    channel: '#my-channel'
    icon_emoji: :robot_face:
