apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-chatops
spec:
  replicas: 1
  selector:
    matchLabels:
      name: k8s-chatops
  template:
    metadata:
      labels:
        name: k8s-chatops
    spec:
      serviceAccountName: k8s-chatops
      containers:
        - name: k8s-chatops
          # Replace this with the built image name
          image: etsauer/k8s-chatops:v0.0.1
          command:
          - events-notifier
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "k8s-chatops"
