kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: events-notifier
subjects:
- kind: ServiceAccount
  name: events-notifier
roleRef:
  kind: Role
  name: events-notifier
  apiGroup: rbac.authorization.k8s.io
